patients/user/forms.py
import re

from flask_wtf import FlaskForm
from wtforms.fields import StringField, PasswordField, SelectField, SelectMultipleField
from wtforms.validators import DataRequired, Length, Regexp


class CreateUserForm(FlaskForm):
    username = StringField('Username', validators=[
        DataRequired(),
        Length(min=6, max=32),
        Regexp(re.compile('^[a-zA-Z-_]+$'),
               message='must contain letters, - and _ only'),
    ])
    password = PasswordField('Password', validators=[
        DataRequired(),
        Length(min=8, max=32),
    ])
    org = SelectField('Org')
    perms = SelectMultipleField('Permissions')

patients/user/views.py
import psycopg2.extras
from flask import (
    Blueprint, flash, redirect, render_template, request, url_for, abort
)
from werkzeug.security import generate_password_hash

from patients.db import get_db
from patients.row_trans import Model, User
from .forms import CreateUserForm

bp = Blueprint('user', __name__, url_prefix='/user')


@bp.route('/', methods=('GET',))
def index():
    db = get_db()
    cur = db.cursor()

    cur.execute(
        'select * from users',
    )
    users = cur.fetchall()
    users = list(map(lambda row: Model(User, row), users))

    cur.close()
    return render_template('user/index.html', users=users)


@bp.route('/create', methods=('GET',))
def create():
    form = CreateUserForm()
    fill_form_org_and_perms(form)
    return render_template('user/create.html', form=form)


@bp.route('/create', methods=('POST',))
def create_post():
    db = get_db()
    cur = db.cursor()
    form = CreateUserForm(request.form)

    fill_form_org_and_perms(form)

    if form.validate():
        cur.execute(
            'select * from users where username=%s',
            (form.username.data,)
        )
        user = cur.fetchone()

        if user:
            form.username.errors.append(
                f'Username {form.username.data} already exists')
            return render_template('user/create.html', form=form)

        cur.execute(
            'insert into users (username, password, org) values (%s, %s, %s)',
            (form.username.data, generate_password_hash(form.password.data), form.org.data)
        )
        db.commit()
        cur.close()

        flash('User created')
        return redirect(url_for('user.index'))

    cur.close()
    return render_template('user/create.html', form=form)


@bp.route('/<username>', methods=('GET',))
def edit(username: str):
    db = get_db()
    cur = db.cursor()

    cur.execute(
        'SELECT * FROM users WHERE username=%s',
        (username,)
    )
    user = cur.fetchone()
    user = Model(User, user)
    if not user:
        abort(404)

    form = CreateUserForm(request.form)
    fill_form_org_and_perms(form)

    form.username.data = user['username']
    form.password.data = '*' * 8
    form.org.data = user['org']
    form.org.default = user['org']
    form.perms.default = []

    cur.close()
    return render_template('user/edit.html', form=form)


@bp.route('/<username>', methods=('POST',))
def edit_post(username: str):
    db = get_db()
    cur = db.cursor()
    err = None

    cur.execute(
        'select * from users where username=%s',
        (username,)
    )
    user = cur.fetchone()
    if not user:
        err = f'User {username} does not exists'

    new_password = request.form['password']

    cur.execute(
        'update users set password = %s where username=%s',
        (generate_password_hash(new_password), username)
    )
    db.commit()
    cur.close()
    flash(err)
    return redirect(url_for('user.index'))


def fill_form_org_and_perms(form: CreateUserForm):
    db = get_db()
    cur = db.cursor(cursor_factory=psycopg2.extras.NamedTupleCursor)

    cur.execute(
        'select * from org',
    )
    orgs = cur.fetchall()

    cur.execute(
        'select * from perm',
    )
    perms = cur.fetchall()

    orgs_list = list(
        map(lambda o: (o.slug, o.slug + ' - ' + o.name), orgs))
    form.org.choices = orgs_list

    perms_list = list(
        map(lambda o: (o.slug, o.slug + ' - ' + o.name), perms)
    )
    form.perms.choices = perms_list

    cur.close()

patients/templates/user/create.html
{% extends 'base.html' %}

{% from "formhelpers.html" import render_field %}


{% block header %}
<h1>{% block title %}Create User{% endblock %}</h1>
{% endblock %}

{% block content %}
<div class="row">
    <div class="col">
        <form method="POST">
            {{ form.hidden_tag() }}
            {{ render_field(form.username) }}
            {{ render_field(form.password) }}
            {{ render_field(form.org) }}
            {{ render_field(form.perms) }}
            <input type="submit" class="btn btn-primary" value="Create">
        </form>
    </div>
</div>
{% endblock %}

patients/templates/user/edit.html
{% extends 'base.html' %}

{% from "formhelpers.html" import render_field %}
{% from "formhelpers.html" import render_field_readonly %}


{% block header %}
<h1>{% block title %}Edit User{% endblock %}</h1>
{% endblock %}

{% block content %}
<div class="row">
    <div class="col">
        <form method="POST">
            {{ form.hidden_tag() }}
            {{ render_field_readonly(form.username) }}
            {{ render_field(form.password) }}
            {{ render_field(form.org) }}
            {{ render_field(form.perms) }}
            <input type="submit" class="btn btn-primary" value="Create">
        </form>
    </div>
</div>
{% endblock %}

patients/templates/user/index.html
{% extends 'base.html' %}

{% block header %}
<h1>{% block title %}All Users{% endblock %}</h1>
{% endblock %}

{% block content %}
<a class="btn btn-success" href="{{ url_for('user.create') }}">New User</a>

<ul>
    {% for user in users %}
    <li>
        <a href="{{ url_for('user.edit', username=user.username) }}">{{user.username}}</a>
        - {{user.created_at}}
    </li>
    {% endfor %}
</ul>

{% endblock %}