patients/res/forms.py
from flask_wtf import FlaskForm
from wtforms import SubmitField, SelectField, IntegerField


class CreateResForm(FlaskForm):
    date = SelectField('Date')
    start_time = SelectField('Start Time')
    end_time = SelectField('End Time')

    cap = IntegerField('Capacity')

    submit = SubmitField('Create Report')

patients/report/views.py
from datetime import datetime

from flask import (
    Blueprint, g, redirect, render_template, request, url_for, abort
)

from patients.auth import login_required
from patients.db import get_db
from patients.report.forms import CreateReportForm, StatePickerForm

bp = Blueprint('report', __name__, url_prefix='/report')


@bp.route('/', methods=('GET',))
def index():
    db = get_db()
    cur = db.cursor()

    state = request.args.get('state', None)
    if state and state != 'all':
        cur.execute(
            'select report.id, p.name from report join patient p on p.id = report.patient where report.state = %s',
            (state,),
        )
    else:
        cur.execute(
            'select report.id, p.name from report join patient p on p.id = report.patient',
        )
    reports = cur.fetchall()

    cur.close()

    state_picker = StatePickerForm()
    state_picker.fill_state_choices()
    return render_template('report/index.html', reports=reports, state_picker=state_picker)


@bp.route('/create', methods=('GET', 'POST'))
@login_required
def create():
    db = get_db()
    cur = db.cursor()
    form = CreateReportForm(request.form)
    fill_form_choices(form)

    form.state.data = 'not-attached'

    if request.method == 'POST' and form.validate():
        cur.execute(
            'insert into report (patient, creator_user, res, state) values (%s, %s, %s, %s)',
            (form.patient.data, g.user.username, form.res.data, form.state.data),
        )
        db.commit()
        cur.close()
        return redirect(url_for('report.index'))

    cur.close()
    return render_template('report/create.html', form=form)


@bp.route('/edit/<int:pk>', methods=('GET', 'POST'))
def edit(pk: int):
    db = get_db()
    cur = db.cursor()

    cur.execute(
        'select * from report where id=%s',
        (pk,),
    )
    report = cur.fetchone()
    if not report:
        abort(404)

    if request.method == 'POST':
        form = CreateReportForm(request.form)
        fill_form_choices(form)

        if form.validate():
            cur.execute(
                'update report set patient = %s, res = %s, state = %s where id=%s',
                (form.patient.data, form.res.data, form.state.data, pk),
            )
            db.commit()
            cur.close()
            return redirect(url_for('report.index'))

        cur.close()
        return render_template('report/edit.html', form=form)

    if request.method == 'GET':
        form = CreateReportForm()
        fill_form_choices(form)
        form.patient.data = str(report.patient)
        form.res.data = report.res
        form.state.data = report.state

        cur.close()
        return render_template('report/edit.html', form=form)


def fill_form_choices(form: CreateReportForm):
    db = get_db()
    cur = db.cursor()
    cur.execute(
        'SELECT * FROM patient',
    )
    form.patient.choices = list(map(lambda p: (p.id, p.name), cur.fetchall()))
    cur.close()

    cur = db.cursor()
    cur.execute(
        "SELECT * FROM res where start_t > timestamp %s",
        (datetime.now().strftime('%Y-%m-%d %H:%M:%S'),),
    )
    form.res.choices = list(map(lambda r: (r.id, f'{r.start_t} - {r.end_t}'), cur.fetchall()))
    cur.close()

    cur = db.cursor()
    cur.execute(
        "SELECT * FROM state",
    )
    form.state.choices = list(map(lambda s: (s.slug, s.name), cur.fetchall()))
    cur.close()

patients/res/__init__.py
from .views import bp

patients/res/views.py
from datetime import date, timedelta, datetime

from flask import (
    Blueprint, redirect, render_template, request, url_for
)

from patients.auth import login_required
from patients.db import get_db
from patients.res.forms import CreateResForm

bp = Blueprint('res', __name__, url_prefix='/res')


@bp.route('/', methods=('GET',))
def index():
    db = get_db()
    cur = db.cursor()

    cur.execute(
        'select res.*, count(r.id) as occupied_cnt from res left join report r on res.id = r.res group by res.id',
    )
    reses = cur.fetchall()

    cur.close()
    return render_template('res/index.html', reses=reses)


@bp.route('/create', methods=('GET', 'POST'))
@login_required
def create():
    db = get_db()
    cur = db.cursor()
    form = CreateResForm(request.form)
    fill_form_choices(form)

    if request.method == 'POST' and form.validate():
        d_start = datetime.strptime(form.date.data, '%Y-%m-%d')
        d_start += timedelta(hours=int(form.start_time.data))
        d_end = datetime.strptime(form.date.data, '%Y-%m-%d')
        d_end += timedelta(hours=int(form.end_time.data))

        cur.execute(
            'insert into res (start_t, end_t, cap) values (%s, %s, %s)',
            (d_start, d_end, form.cap.data),
        )
        db.commit()
        cur.close()
        return redirect(url_for('res.index'))

    cur.close()
    return render_template('res/create.html', form=form)


@bp.route('/<int:pk>/details', methods=('GET',))
@login_required
def details(pk: int):
    db = get_db()
    cur = db.cursor()

    cur.execute(
        'select * from res where id = %s',
        (pk,),
    )
    res = cur.fetchone()

    cur.execute(
        'select p.id as pid, p.name, r.* from report r join patient p on p.id = r.patient where r.res = %s',
        (pk,),
    )
    reports = cur.fetchall()

    cur.close()
    return render_template('res/details.html', res=res, reports=reports)


def fill_form_choices(form: CreateResForm):
    date_choices = []
    for i in range(30):
        d = date.today() + timedelta(days=i)
        date_choices.append(
            (d.strftime('%Y-%m-%d'), d.strftime('%Y/%m/%d'))
        )

    time_choices = []
    for i in range(24):
        time_choices.append(
            (str(i), f'{i}:00')
        )

    form.date.choices = date_choices
    form.start_time.choices = time_choices
    form.end_time.choices = time_choices

patients/templates/res/create.html
{% extends 'base.html' %}

{% from "formhelpers.html" import render_field %}


{% block header %}
    <h1>{% block title %}Create Report{% endblock %}</h1>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col">
            <form method="POST">
                {{ form.hidden_tag() }}
                {{ render_field(form.date) }}
                {{ render_field(form.start_time) }}
                {{ render_field(form.end_time) }}
                {{ render_field(form.cap) }}
                <input type="submit" class="btn btn-primary" value="Create">
            </form>
        </div>
    </div>
{% endblock %}

patients/templates/res/details.html
{% extends 'base.html' %}

{% block header %}
    <h1>{% block title %}Reservation Details{% endblock %}</h1>
{% endblock %}

{% block content %}

    <div class="col-md-12">
        <h3>List of reports for this reservation time span</h3>
        <p>[{{ res.cap }}] - {{ res.start_t }} to {{ res.end_t }}</p>
        <ul>
            {% for report in reports %}
                <li>
                    <a href="{{ url_for('report.edit', pk=report.id) }}">{{ report.name }} - {{ report.state }}</a>
                </li>
            {% endfor %}
        </ul>
    </div>

{% endblock %}

patients/templates/res/index.html
{% extends 'base.html' %}

{% block header %}
    <h1>{% block title %}All Reservations{% endblock %}</h1>
{% endblock %}

{% block content %}

    <div class="col-md-12">
        <a class="btn btn-success" href="{{ url_for('res.create') }}">New Reservation</a>
        <ul>
            {% for res in reses %}
                <li>
                    <a href="{{ url_for('res.details', pk=res.id) }}">[{{ res.occupied_cnt }}(occupied) / {{ res.cap }}] - {{ res.start_t }}
                        to {{ res.end_t }}</a>
                </li>
            {% endfor %}
        </ul>
    </div>

{% endblock %}